### ISSUE TITLE
Code comments

### ISSUE THREAD

**Issue by geo7** [bazzilic/LaTeXpkges#1]
Hi, not sure if you're maintaining this as well or just hosting it, but it would be nice to have comments for the functions and such for others (such as myself) to read. 

I was just thinking about something like this for use with Linux

Cheers

**Comment by bazzilic** [comment]
I wrote the script but don't really maintain it. I am not aware of any bugs in it, so there's not much to do about it. The only parts where it might need to be fixed to work on *nix systems is calls to the filesystem API: file path handling, `/` instead of `\`, etc.

**Comment by geo7** [comment]
Hmm OK - I'll have to have more of an in depth read then ;) 

I think that it could be useful for something such as sharing .TeX files or LaTeX work in a way that's 'all in one' rather than split across multiple files / directories (which is how I have a template), as well as the obvious use of trimming packages down from a project. 

If I get chance I'll have a look at it and try it out on Linux. 

Nice one.
