### ISSUE TITLE
How does it work????

### ISSUE THREAD

**Issue by pauloney** [bazzilic/LaTeXpkges#2]
Bazzilic, would you please explain how the program works? If two PDF identical files are generated 1 minute apart - they had different metadata and the md5sum's of both will be different ... so I am not sure I understand how are the files compared.

**Comment by bazzilic** [comment]
Before the MD5 hash of the PDF is calculated for comparison, the script goes through the PDF and removes the metadata that is typically created by pdflatex. Please also refer to https://github.com/bazzilic/LaTeXpkges/blob/master/LaTeXpkges.py#L117, lines 118–124

**Comment by pauloney** [comment]
Dear Vasily, we at BooksinBytes just ported the program to Linux, in fact we made it OS agnostic, so the same code will run on all machines -- making the program more useful to more people. Taras Kuzyo, one of the engineers that work for us on this project has just send you a pull-request for that. We are planning on doing a lot more like, make it allow one to choose in between latex/pdflatex/xelatex/lualatex, to be able to choose among bibtex/biblatex/none, to run it on copies of the files rather than on the main file... not depending on giving the path, etc ... and we will send you these as they get ready!
